# Step 1/25 : 
# Step 2/25 : 
# Step 3/25 : 
# Step 4/25 : 
# Step 5/25 : 
# Step 6/25 : 
# Step 7/25 : 
# Step 8/25 : 
# Step 9/25 : 
# Step 10/25 : 
# Step 11/25 : 
# Step 12/25 : 
FROM mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20220314.v1
ARG DEBIAN_FRONTEND=noninteractive
ARG ACCEPT_EULA=Y
RUN apt-get update -y && apt-get upgrade -y &&    apt-get install -y build-essential                        
RUN echo "Hello from custom container!" > ~/hello.txt
USER root
RUN mkdir -p $HOME/.cache
WORKDIR /
COPY azureml-environment-setup/99brokenproxy /etc/apt/apt.conf.d/
RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.11; then conda install conda==4.
COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_2d420815558f487c97f8686291bca2c8 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find 